{{ if not (and .Values.database.existingSecret (and ( .Values.smtp.existingSecret ) ( .Values.adminToken.existingSecret ))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
type: Opaque
data:
  {{- if not ( .Values.database.existingSecret ) }}
  {{- if ne "default" .Values.database.type }}
  {{- if .Values.database.uriOverride }}
  DATABASE_URL: {{ .Values.database.uriOverride | b64enc | quote }}
  {{- else }}
  DATABASE_URL: {{ include "dbString" . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if not ( .Values.smtp.existingSecret ) }}
  SMTP_PASSWORD: {{ .Values.smtp.password.value | b64enc | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username.value | b64enc | quote }}
  {{- end }}
  {{- if not ( .Values.adminToken.existingSecret ) }}
  ADMIN_TOKEN: {{ .Values.adminToken.value | b64enc | quote }}
  {{- end }}
{{ end }}
