apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: 'filebrowser/filebrowser:v2.1.0'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
  labels:
    name: filebrowser-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: HTTP
  selector:
    app: filebrowser
  type: ClusterIP
