apiVersion: v1
kind: Service
metadata:
  name: {{ include "ahparser.fullname" . }}
  labels:
    {{- include "ahparser.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ahparser.service.type }}
  ports:
    - port: {{ .Values.ahparser.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ahparser.selectorLabels" . | nindent 4 }}
