apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ahparser.fullname" . }}
  labels:
    {{- include "ahparser.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ahparser.fullname" . }}
  {{- if and (.Values.ahparser.replicaCount) }}
  replicas: {{ .Values.ahparser.replicaCount }}
  {{- end }}
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ahparser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ahparser.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ahparser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ahparser
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ahparser.image.repository }}:{{ .Values.ahparser.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ahparser.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ahparser.service.internalPort | default 3000 }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.ahparser.service.internalPort | default 3000 | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "ahparser.configMapRef" . }}
            - secretRef:
                name: {{ include "ahparser.secretRef" . }}
          {{- if .Values.probesEnabled }}
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 12
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 20
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.ahparser.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
