{{- if not .Values.config.existingRef }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ahparser.configMapRef" . }}
  labels:
    {{- include "ahparser.labels" . | nindent 4 }}
data:
  REGISTER_ENABLED: {{ .Values.config.ahparser.registerEnabled | quote }}
{{- end}}
