{{- if not .Values.secrets.existingRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ahparser.secretRef" . }}
  labels:
    {{- include "ahparser.labels" . | nindent 4 }}
stringData:
  IMAP_HOST: {{ .Values.secrets.mail.host | quote }}
  IMAP_PORT: {{ .Values.secrets.mail.port | quote }}
  IMAP_USER: {{ .Values.secrets.mail.username | quote }}
  IMAP_PASSWORD: {{ .Values.secrets.mail.password | quote }}
  IMAP_TLS: {{ .Values.secrets.mail.tls | quote }}

  MYSQL_HOST: {{ .Values.secrets.db.host | quote }}
  MYSQL_PORT: {{ .Values.secrets.db.port | quote }}
  MYSQL_USER: {{ .Values.secrets.db.username | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.db.password | quote }}
  MYSQL_DATABASE: {{ .Values.secrets.db.database | quote }}
{{- end}}
