name: Bump Chart Versions

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  update-chart-versions:
    name: Update Chart Versions
    runs-on: ubuntu-latest
    if: ${{ needs.changed-files.outputs.any_changed == 'true' && github.actor == 'renovate[bot]' }}
    needs: [changed-files]
    strategy:
      matrix:
        charts: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Chart Version
        env:
          CHART: ${{ matrix.charts }}
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          echo "Bumping $CHART"
          ./scripts/bumpversion-helmchart.sh

      - name: Commit Changes
        run: |
          echo ${{ github.ref_name }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m 'chore(deps): updated chart ${{ matrix.charts }}' || echo "Nothing to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: "${{ github.ref_name }}"

  changed-files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      any_changed: ${{ steps.changed-files-specific.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changed charts
        id: changed-files-specific
        uses: tj-actions/changed-files@v40
        with:
          files: |
            charts/**
          json: true

      - id: set-matrix
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          set -eux
          DATA=$(echo ${{ steps.changed-files-specific.outputs.all_changed_files }} | jq -c '. | map(split("/")[1]) | unique')
          echo "matrix=$DATA" >> "$GITHUB_OUTPUT"
